---
# tasks file for test-role
- name: Include distribution and version-specific vars.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{  ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{  ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}.yml'

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Write fact if software needs to be installed
  ansible.builtin.set_fact:
    global_var: true
  #when: "'managesoft' not in ansible_facts.packages or managesoft_force"

- name: Include distribution and version-specific tasks.
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - 'setup-{{ ansible_distribution }}-{{  ansible_distribution_major_version }}.yml'
        - 'setup-{{ ansible_distribution }}.yml'
        - 'setup-{{ ansible_os_family }}.yml'
