---
- hosts: all
  become: true
  tasks:
  vars:
   download_url: https://download.oracle.com/otn-pub/java/jdk/12.0.1+12/69cfe15208a647278a19ef0990eea691/jdk-12.0.1_linux-x64_bin.rpm 
  tasks:
  - name: Download JDK 11 RPM file
    command: "wget --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} "
  - name: Install JDK 11
    command: "rpm -ivh jdk-12.0.1_linux-x64_bin.rpm"
