---
- hosts: all
  become: true
  tasks:
   - name: Download Maven
     get_url: url=http://us.mirrors.quenda.co/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz dest=/opt/niranjan/apache-maven-3.6.1-bin.tar.gz
   - name: Extract Maven
     command: tar xvf /opt/niranjan/apache-maven-3.6.1-bin.tar.gz -C /opt/niranjan
   - name: Move to a smaller directory
     command: mv /opt/niranjan/apache-maven-3.6.1 /opt/niranjan/maven
   - name: Update Profile
     copy: content="export M2_HOME=/opt/niranjan/maven \n" dest=/etc/profile.d/maven.sh
    # lineinfile is used to add additional or append lines to existing files.
   - lineinfile:
        path: /etc/profile.d/maven.sh
        line: 'export PATH=${M2_HOME}/bin:${PATH}'
  #- name: Source profile
  #  shell: source /etc/profile.d/maven.sh
